# Gitignore Global
## GLOBAL - macOS .gitignore
### General

######
## Mac OS
######

#### MacOS - System generated files
.AppleDouble
.LSOverride
Desktop.ini
.DS_Store?
ehthumbs.db
Icon?
Thumbs.db
*.DS_Store
######

#### MacOS - Files that might appear in the root of a volume
######
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent
######

#### MacOS - Directories potentially created on remote AFP share
######
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk
######

#### MacOS -  Runtime data
######
pids
*.pid
*.seed
*.pid.lock
######

#### MacOS - Icons
###### **Icon must end with two \r*
######
Icon
######

#### # Thumbnails
######
._*
######

#### MacOS - Folder view configuration files
######
Desktop.ini
######

#### MacOS - Logs
######
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
######

#### MacOS - Other
#####  Files that might appear in the root of a volume
######
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent
######

### Other - Logs
######

###### Crash log files
crash.log
######

## Environment Variables
##### dotenv environment variable files
######
.env*
######


## Application specific files
######

### Xcode
######
*.pbxuser
*.mode1v3
*.mode2v3
*.perspectivev3
*.xcuserstate
project.xcworkspace/
xcuserdata/
######

### VS CODE
######
.vscode
Thumbs.db
######


######
### Adobe
##### Adobe Idea
###### Image created by Adobe Ideas, a vector image editing touch app for Android tablets; can include vector objects, layers, color themes, and other graphics; 
.idea
######

### NodeJS

###### Dependency directories
######
node_modules/
jspm_packages/
######

### Yarn
######
yarn-error.log
.pnp/
.pnp.js
######

#### Yarn Integrity file
.yarn-integrity
######

### NPM
##### NPM - Optional npm cache directory
######
.npm
######

##### Output of 'npm pack'
*.tgz
######

## Miscalaneous 

#### #SASS
###### Sass Cache
.sass-cache

#### # JSCover:
###### Directory for instrumented libs generated by jscoverage/JSCover
######
lib-cov
######

#### # Istanbul:
###### Coverage directory used by tools like istanbul
######
coverage
######

#### # Keystone:
###### nyc test coverage
######
.nyc_output
######

#### # Grunt:
###### Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
######
.grunt
######

#### # Bower:
###### Bower dependency directory (https://bower.io/)
######
bower_components
######

#### # node-waf configuration:
######
.lock-wscript
######

###### Compiled binary addons (http://nodejs.org/api/addons.html)
######
build/Release
######

####  # eslint
###### Optional eslint cache
.eslintcache
######
####  # REPL
###### Optional REPL history
.node_repl_history
######

##### gatsby files
######
.cache/
public
######

## Language Specific Files
######

### TypeScript
###### Typescript v1 declaration files
######
typings/
######

##### Directories potentially created on remote AFP share
######
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk
######

### Python
###### Compiled Python files
######
*.pyc
######

### C++
###### Compiled C++ files
######
*.out
######

##### Other files
######
venv
######

#####  *Key
######
###### ### Catetory (3 #)
###### #### Sub Catetory (4 #)
###### ##### Extensions (5 #)
######
